// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbs_sampler_cpp
NumericVector gibbs_sampler_cpp(int n_iter, NumericVector y, double start_theta);
RcppExport SEXP _SA25204152_gibbs_sampler_cpp(SEXP n_iterSEXP, SEXP ySEXP, SEXP start_thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type start_theta(start_thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_sampler_cpp(n_iter, y, start_theta));
    return rcpp_result_gen;
END_RCPP
}
// calc_psi_cpp
arma::mat calc_psi_cpp(const Rcpp::List& K_list);
RcppExport SEXP _SA25204152_calc_psi_cpp(SEXP K_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type K_list(K_listSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_psi_cpp(K_list));
    return rcpp_result_gen;
END_RCPP
}
// fit_cpe_cpp
arma::mat fit_cpe_cpp(const Rcpp::List& K_list, arma::mat G_init, int max_iter, double tol);
RcppExport SEXP _SA25204152_fit_cpe_cpp(SEXP K_listSEXP, SEXP G_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type K_list(K_listSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G_init(G_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_cpe_cpp(K_list, G_init, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA25204152_gibbs_sampler_cpp", (DL_FUNC) &_SA25204152_gibbs_sampler_cpp, 3},
    {"_SA25204152_calc_psi_cpp", (DL_FUNC) &_SA25204152_calc_psi_cpp, 1},
    {"_SA25204152_fit_cpe_cpp", (DL_FUNC) &_SA25204152_fit_cpe_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA25204152(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
