# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A Gibbs Sampler using Rcpp
#'
#' @param n_iter Number of iterations
#' @param y Input vector
#' @param start_theta Initial value
#' @return A vector of samples
#' @export
gibbs_sampler_cpp <- function(n_iter, y, start_theta) {
    .Call(`_SA25204152_gibbs_sampler_cpp`, n_iter, y, start_theta)
}

#' Calculate Aggregated Projection Matrix (Core for APM)
#'
#' @param K_list A list of matrices (T x r) representing factor spaces for each group.
#' @return A matrix (T x T) representing the average projection matrix.
calc_psi_cpp <- function(K_list) {
    .Call(`_SA25204152_calc_psi_cpp`, K_list)
}

fit_cpe_cpp <- function(K_list, G_init, max_iter = 100L, tol = 1e-6) {
    .Call(`_SA25204152_fit_cpe_cpp`, K_list, G_init, max_iter, tol)
}

